version: "3.7"

services:
  cloud_functions:
    build: ./
    command: yarn serve
    user: node
    ports:
      - "5000:5000"
      - "9005:9005"
    volumes:
      - ~/.config/wiggles-service-account.json:/home/node/wiggles-service-account.json
      - ./:/app
      - /app/functions/node_modules
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/node/wiggles-service-account.json
      - FIREBASE_TOKEN
