version: "3.7"

services:
  cloud_functions:
    build: ./
    command: yarn serve -o 0.0.0.0
    ports:
      - "5000:5000"
      - "9005:9005"
    volumes:
      - ./.config:/root/.config
      - ./:/app
      - /app/functions/node_modules
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/service-account.json
