version: "3.7"

services:
  cloud_functions:
    build: ./
    command: yarn serve
    ports:
      - "5000:5000"
      - "9005:9005"
    volumes:
      - ./:/app
      - /app/functions/node_modules
      - ./.config:/root/.config
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/service-account.json
